name: Build and Test

description: Restores dependencies, builds, and runs tests.

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v5

    - name: Restore
      shell: bash
      run: dotnet restore

    - name: Build
      shell: bash
      run: dotnet build -c Release --no-restore

    - name: Test
      shell: bash
      run: dotnet test -c Release --no-build --logger trx --results-directory TestResults
