name: Build

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-and-test
