name: CI

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: Format
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/check-formatting

  build-test:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/build-and-test

      - name: Upload TRX test results
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: trx-test-results
          if-no-files-found: warn
          path: TestResults/**

  package:
    name: Package ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/create-release-artifacts
        with:
          arch: ${{ matrix.arch }}
          artifact-name: desktopclock-${{ matrix.arch }}
