name: Release and deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '0.0.0'
      updateRelease:
        description: 'Update existing release'
        required: true
        type: boolean
        default: false
      dryRun:
        description: 'Dry run'
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build-and-test

      - name: Package x64
        uses: ./.github/actions/create-release-artifacts
        with:
          version: ${{ inputs.version }}
          arch: x64

      - name: Package arm64
        uses: ./.github/actions/create-release-artifacts
        with:
          version: ${{ inputs.version }}
          arch: arm64

      - name: Create GitHub release
        if: ${{ !inputs.dryRun }}
        uses: ncipollo/release-action@v1.21.0
        with:
          tag: "v${{ inputs.version }}"
          artifacts: "publish/*.zip,publish/*.msi"
          generateReleaseNotes: true
          prerelease: ${{ contains(inputs.version, '-') }}
          allowUpdates: ${{ inputs.updateRelease }}
          removeArtifacts: true
          omitBodyDuringUpdate: true
